### ISSUE TITLE
Dimensional Warp Prisms not sending across dimensions

### ISSUE THREAD

**Issue by Witherslayer564** [Vonr/Ars-Controle#2]
Hello, I am currently making a cross dimensional device that will heavily rely on your warp prisms, however, it seems that the prism doesn't send the projectiles across dimensions like it says. I would fire test shots consisting of 'Projectile -> Mageblock' through as a test from the overworld to the nether, and nothing would appear on the other side. I will say it DOES work when it goes across the same dimension. I don't know if I am simply doing it wrong, but I really like your mod so far, and am excited to see it through!

**Comment by Vonr** [comment]
If this is on 1.20, you will need both sides (prism/turret and prism target) to be chunk loaded.

**Comment by Witherslayer564** [comment]
I am currently using multiple chunk loader mods to keep the chunks loaded, but still no dice. I have both sides loaded by several varieties of chunk loader blocks.

**Comment by Witherslayer564** [comment]
I have just found a method to allow them to load in my game! Using the built-in Ars Nouveau chunk loader ritual tablet worked. Sorry for wasting your time, and thank you for your help!

**Comment by Vonr** [comment]
You did help me find a bug in 1.21 though haha, will be fixed in next release.
